Emerge now uses chrooted host

diff --git a/crossdev-cow-env-chroot b/crossdev-cow-env-chroot
--- a/crossdev-cow-env-chroot
+++ b/crossdev-cow-env-chroot
@@ -1,13 +1,72 @@
 #!/bin/bash
 
+CD_ENV_ARGS=()
+CD_COW_CHROOT_ARGS=()
+
 CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")
 
 source "${CD_CUR_DIR}/crossdev-functions.sh"
 
 cd_parse_arguments $@
 
+cd_parse_extra_arguments() {
+
+  while (( ${#1} )); do
+    case ${1} in
+      *-cd-env-dir)
+      shift; CD_ENV_DIR="${1}"
+      ;;
+      *-cd-env-dir=*)
+      CD_ENV_DIR="${1#*=}"
+      ;;
+      *-cd-chroot-target-dir)
+      shift; CD_CHROOT_TARGET_DIR="${1}"
+      ;;
+      *-cd-chroot-target-dir=*)
+      CD_CHROOT_TARGET_DIR="${1#*=}"
+      ;;
+      *-cd-chroot-wrapper-dir)
+      shift; CD_CHROOT_WRAPPER_DIR="${1}"
+      ;;
+      *-cd-chroot-wrapper-dir=*)
+      CD_CHROOT_WRAPPER_DIR="${1#*=}"
+      ;;
+      --)
+      shift;
+      while (( ${#@} )); do
+        CD_COW_CHROOT_ARGS+=(${1})
+        shift
+      done
+      break
+      ;;
+      *)
+      CD_COW_CHROOT_ARGS+=(${1})
+      ;;
+    esac
+    shift
+  done
+
+  if [ -z "${CD_ENV_DIR}" ]; then
+    export CD_ENV_DIR=${CD_TMP_DIR}/env-${CD_TARGET}
+  fi
+
+  if [ -z "${CD_CHROOT_TARGET_DIR}" ]; then
+    export CD_CHROOT_TARGET_DIR="${TARGET_DIR}"
+  fi
+
+  if [ -z "${CD_CHROOT_WRAPPER_DIR}" ]; then
+    export CD_CHROOT_WRAPPER_DIR="${CD_TMP_DIR}/wrapper-${CD_HOST}"
+  fi
+
+}
+
+cd_parse_extra_arguments "${CD_ARGS[@]}"
+
 if [ ! -z "${CD_HELP}" ]; then
   cd_print_usage_header
+  echo "--cd-env-dir <dir> (Environment dir) (${CD_ENV_DIR}}"
+  echo "--cd-chroot-target-dir <dir> (Target dir in chroot) (${CD_CHROOT_TARGET_DIR}}"
+  echo "--cd-chroot-wrapper-dir <dir> (Wrapper dir in chroot) (${CD_CHROOT_WRAPPER_DIR}}"
   exit 1
 fi
 
@@ -17,27 +76,64 @@ else
   export CD_CUR_DIR=${PWD}
 fi
 
-export CD_COW_DIR=${CD_TMP_DIR}/cow-${CD_TARGET}
-export CD_UNION_DIR=${CD_TMP_DIR}/union-${CD_TARGET}
-export CD_COW_WRAPPER_DIR=${CD_TMP_DIR}/wrapper-cow-${CD_TARGET}
+export CD_ENV_COW_DIR=${CD_ENV_DIR}/cow-${CD_TARGET}
+export CD_ENV_WORK_DIR=${CD_ENV_DIR}/work-${CD_TARGET}
+export CD_ENV_UNION_DIR=${CD_ENV_DIR}/union-${CD_TARGET}
+export CD_ENV_OVERLAY_DIR=${CD_ENV_DIR}/overlay-${CD_TARGET}
 
 if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-pre" ]; then
   source "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-pre" || cd_die
 fi
 
-if ! cd_is_mount "${CD_UNION_DIR}"; then
-CD_QUIET=1 "${CD_SCRIPT_DIR}/crossdev-cow-env-init" "${CD_ARGS[@]}" || cd_die
+if ! cd_is_mount "${CD_ENV_UNION_DIR}"; then
+"${CD_SCRIPT_DIR}/crossdev-cow-env-init" "${CD_COW_CHROOT_ARGS[@]}" || cd_die
 fi
 
-if cd_is_mount "${CD_UNION_DIR}"; then
-  export SANDBOX_WRITE=${SANDBOX_WRITE}:${CD_TARGET_DIR%/}
-  if (( ${#CD_ARGS[@]} )); then
-    chroot "${CD_UNION_DIR}" /usr/bin/env -u ROOT -u PORTAGE_CONFIGROOT -C "${CD_CUR_DIR}" CD_CHROOT_ENV=1 CD_COW_ENV_CHROOT=1 /bin/bash /profile "${CD_ARGS[@]}" || cd_die
+if cd_is_mount "${CD_ENV_UNION_DIR}"; then
+  CD_ENV_ARGS+=("-u ROOT")
+  CD_ENV_ARGS+=("-u SYSROOT")
+  CD_ENV_ARGS+=("-u CD_TARGET")
+  CD_ENV_ARGS+=("-u CD_CUR_DIR")
+  CD_ENV_ARGS+=("-u CD_PREFIX_DIR")
+  CD_ENV_ARGS+=("-u CD_TARGET_DIR")
+  CD_ENV_ARGS+=("-u PORTAGE_CONFIGROOT")
+
+  CD_ENV_ARGS+=("CD_CHROOT_ENV=1")
+  CD_ENV_ARGS+=("CD_COW_ENV_CHROOT=1")
+  
+  CD_ENV_ARGS+=("ROOT=${CD_CHROOT_TARGET_DIR}")
+  CD_ENV_ARGS+=("SYSROOT=${CD_CHROOT_TARGET_DIR}")
+
+  if [ "${CD_HOST}" != "${CD_TARGET}" ]; then
+    CD_ENV_ARGS+=("CD_HOST_DIR=/")
+    CD_ENV_ARGS+=("CD_HOST=${CD_TARGET}")
   else
-    chroot "${CD_UNION_DIR}" /usr/bin/env -u ROOT -u PORTAGE_CONFIGROOT -C "${CD_CUR_DIR}" CD_CHROOT_ENV=1 CD_COW_ENV_CHROOT=1 CD_COW_ENV_CHROOT_ENTER=1 /bin/bash --rcfile "/profile" || cd_die
+    CD_ENV_ARGS+=("PORTAGE_CONFIGROOT=${CD_CHROOT_TARGET_DIR}")
+  fi
+
+  CD_ENV_ARGS+=("PYTHONPATH=${CD_CHROOT_WRAPPER_DIR}/lib")
+  CD_ENV_ARGS+=("_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata")
+
+  CD_ENV_ARGS+=("CC_host=${CD_CHROOT_WRAPPER_DIR}/bin/${CD_HOST}-gcc")
+  CD_ENV_ARGS+=("CXX_host=${CD_CHROOT_WRAPPER_DIR}/bin/${CD_HOST}-g++")
+  CD_ENV_ARGS+=("CPP_host=${CD_CHROOT_WRAPPER_DIR}/bin/${CD_HOST}-cpp")
+
+  CD_ENV_ARGS+=("CC_target=${CD_CHROOT_WRAPPER_DIR}/bin/${CD_TARGET}-gcc")
+  CD_ENV_ARGS+=("CXX_target=${CD_CHROOT_WRAPPER_DIR}/bin/${CD_TARGET}-g++")
+  CD_ENV_ARGS+=("CPP_target=${CD_CHROOT_WRAPPER_DIR}/bin/${CD_TARGET}-cpp")
+
+  CD_ENV_ARGS+=("CD_PATH=${CD_CHROOT_WRAPPER_DIR}/bin${PREROOTPATH+:}${PREROOTPATH}:${PATH}")
+  CD_ENV_ARGS+=("PREROOTPATH=${CD_CHROOT_WRAPPER_DIR}/bin${PREROOTPATH+:}${PREROOTPATH}:${PATH}")
+
+  export SANDBOX_WRITE=${SANDBOX_WRITE}:${CD_ENV_DIR%/}
+
+  if (( ${#CD_COW_CHROOT_ARGS[@]} )); then
+    chroot "${CD_ENV_UNION_DIR}" /usr/bin/env ${CD_ENV_ARGS[@]} /bin/bash /profile "${CD_COW_CHROOT_ARGS[@]}" || cd_die
+  else
+    chroot "${CD_ENV_UNION_DIR}" /usr/bin/env ${CD_ENV_ARGS[@]} CD_COW_ENV_CHROOT_ENTER=1 /bin/bash --rcfile "/profile" || cd_die
   fi
 else
-  eerror "Union prefix dir ${CD_UNION_DIR} does not exist, cannot chroot"
+  eerror "Union prefix dir ${CD_ENV_UNION_DIR} does not exist, cannot chroot"
 fi
 
 if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-post" ]; then
