Using openrc init functions Added command line option parsingV

diff --git a/crossdev-cow-env-enter b/crossdev-cow-env-enter
--- a/crossdev-cow-env-enter
+++ b/crossdev-cow-env-enter
@@ -1,31 +1,42 @@
 #!/bin/bash
 
-TARGET=$1
-shift
-TARGET_DIR=$1
-shift
-SCRIPT_DIR=$(dirname "$0")
+CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
+CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")
 
-if [[ -z "${TARGET_DIR}" ]]; then
-  TARGET_DIR="/usr/${TARGET}"
+source "${CD_SCRIPT_DIR}/crossdev-functions.sh"
+
+cd_parse_arguments $@
+
+if [[ ! -z "${CD_HELP}" ]]; then
+  cd_print_usage_header
+  exit 1
 fi
 
-is_mount() {
-  path=$(readlink -f $1)
-  grep -q "$path" /proc/mounts
-}
+CD_COW_PREFIX_DIR=/tmp/cow-${CD_TARGET}
+CD_UNION_PREFIX_DIR=/tmp/union-${CD_TARGET}
 
-COW_PREFIX_DIR=/tmp/cow-${TARGET}
-UNION_PREFIX_DIR=/tmp/union-${TARGET}
-
-if [[ -f "${SCRIPT_DIR}/crossdev-cow-env-enter-pre" ]]; then
-  source "${SCRIPT_DIR}/crossdev-cow-env-enter-pre"
+if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-bashrc" ]; then
+  CD_BASH_RC_FILE="${CD_CONFIG_DIR}/crossdev-cow-env-bashrc"
+else
+  CD_BASH_RC_FILE="${CD_SCRIPT_DIR}/crossdev-cow-env-bashrc"
 fi
 
-if is_mount "${UNION_PREFIX_DIR}"; then
-  chroot ${UNION_PREFIX_DIR} /usr/bin/env -i TARGET="${TARGET}" COWHOME="${PWD}" HOME="${HOME}" TERM="${TERM}" PS1="${PS1}" /bin/bash --rcfile ${PWD}/crossdev-cow-env-bashrc
+if [[ -f "${CD_CONFIG_DIR}/crossdev-cow-env-enter-pre" ]]; then
+  ebegin "Executing crossdev cow env enter pre hook"
+  source "${CD_CONFIG_DIR}/crossdev-cow-env-enter-pre" || cd_die
+  eend 0
 fi
 
-if [[ -f "${SCRIPT_DIR}/crossdev-cow-env-enter-post" ]]; then
-  source "${SCRIPT_DIR}/crossdev-cow-env-enter-post"
+if cd_is_mount "${CD_UNION_PREFIX_DIR}"; then
+  ebegin "Entering environment"
+  chroot ${CD_UNION_PREFIX_DIR} /usr/bin/env -i CD_TARGET="${CD_TARGET}" CD_COWHOME="${PWD}" HOME="${HOME}" TERM="${TERM}" PS1="${PS1}" /bin/bash --rcfile "${CD_BASH_RC_FILE}" || cd_die
+  eend 0
+else
+  eerror "Union prefix dir ${CD_UNION_PREFIX_DIR} does not exist, cannot enter"
+fi
+
+if [[ -f "${CD_CONFIG_DIR}/crossdev-cow-env-enter-post" ]]; then
+  ebegin "Executing crossdev cow env enter post hook"
+  source "${CD_CONFIG_DIR}/crossdev-cow-env-enter-post" || cd_die
+  eend 0
 fi
diff --git a/crossdev-install-qemu-wrapper b/crossdev-install-qemu-wrapper
--- a/crossdev-install-qemu-wrapper
+++ b/crossdev-install-qemu-wrapper
@@ -1,22 +1,57 @@
 #!/bin/bash
 
-TARGET=$1
-shift
-TARGET_DIR=$1
-shift
-ARCH=$1
-shift
-SCRIPT_DIR=$(dirname "$0")
+CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
+CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")
 
-if [[ -z "${TARGET_DIR}" ]]; then
-  TARGET_DIR="/usr/${TARGET}"
+source "${CD_SCRIPT_DIR}/crossdev-functions.sh"
+
+cd_parse_arguments $@
+
+cd_parse_extra_arguments() {
+
+  while (( ${#1} )); do
+    case ${1} in
+      --cd-qemu-arch)
+      shift; CD_QEMU_ARCH=${1}
+      ;;
+    esac
+    shift
+  done
+
+  if [[ ! -z "${CD_QEMU_ARCH}" ]]; then
+    einfo "Using qemu arch: ${CD_QEMU_ARCH}";
+  else
+    eerror "No qemu arch specified, use --cd-qemu-arch";
+    CD_HELP=1
+  fi
+
+}
+
+cd_parse_extra_arguments "${CD_ARGS[@]}"
+
+if [[ ! -z "${CD_HELP}" ]]; then
+  cd_print_usage_header
+  echo "--cd-qemu-arch (Architecture part of user emulation binary)"
+  exit 1
 fi
 
-if [ -d "${TARGET_DIR}" ]; then
-
-  cp -a /usr/bin/qemu-${ARCH} ${TARGET_DIR}/usr/bin/qemu-${ARCH}-real
-  gcc -static ${SCRIPT_DIR}/crossdev-qemu-wrapper/qemu-wrapper-${TARGET}.c -O3 -s -o /tmp/qemu-wrapper-${TARGET}
-  cp -a /tmp/qemu-wrapper-${TARGET} ${TARGET_DIR}/usr/bin/qemu-${ARCH}
-  rm -f /tmp/qemu-wrapper-${TARGET}
-
+if [ -d "${CD_TARGET_DIR}" ]; then
+  if [ -f "/usr/bin/qemu-${CD_QEMU_ARCH}" ]; then
+    if [ -f "${CD_SCRIPT_DIR}/crossdev-qemu-wrapper/qemu-wrapper-${CD_TARGET}.c" ]; then
+        ebegin "Installing qemu user emulation in ${CD_TARGET_DIR} for ${CD_QEMU_ARCH} using a custom wrapper"
+        cp -a "/usr/bin/qemu-${CD_QEMU_ARCH}" "${CD_TARGET_DIR}/usr/bin/qemu-${CD_QEMU_ARCH}-real" || cd_die
+        gcc -static "${CD_SCRIPT_DIR}/crossdev-qemu-wrapper/qemu-wrapper-${CD_TARGET}.c" -O3 -s -o "/tmp/qemu-wrapper-${CD_TARGET}" || cd_die
+        cp -a "/tmp/qemu-wrapper-${CD_TARGET}" "${CD_TARGET_DIR}/usr/bin/qemu-${CD_QEMU_ARCH}" || cd_die
+        rm -f "/tmp/qemu-wrapper-${CD_TARGET}" || cd_die
+        eend 0
+    else
+        ebegin "Installing qemu user emulation in ${CD_TARGET_DIR} for ${CD_QEMU_ARCH} not using a custom wrapper"
+        cp -a "/usr/bin/qemu-${CD_QEMU_ARCH}" "${CD_TARGET_DIR}/usr/bin/qemu-${CD_QEMU_ARCH}" || cd_die
+        eend 0
+    fi
+  else
+    eerror "No qemu user emulation binary for ${CD_TARGET} found, rebuild qemu with USE=\"qemu_user_targets_${CD_QEMU_ARCH}\""
+  fi
+else 
+  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot install qemu user emulation"
 fi
diff --git a/crossdev-install-rpi3-firmware b/crossdev-install-rpi3-firmware
--- a/crossdev-install-rpi3-firmware
+++ b/crossdev-install-rpi3-firmware
@@ -1,31 +1,37 @@
 #!/bin/bash
 
-TARGET=$1
-shift
-TARGET_DIR=$1
-shift
-ARCH=$1
-shift
-SCRIPT_DIR=$(dirname "$0")
+CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
+CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")
 
-if [[ -z "${TARGET_DIR}" ]]; then
-  TARGET_DIR="/usr/${TARGET}"
+source "${CD_SCRIPT_DIR}/crossdev-functions.sh"
+
+cd_parse_arguments $@
+
+if [[ ! -z "${CD_HELP}" ]]; then
+  cd_print_usage_header
+  exit 1
 fi
 
-if [ ! -f "${TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image" ]; then
-  echo "Build ${TARGET} kernel in \"${TARGET_DIR}\" first, exiting"; exit 0
+if [ ! -f "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image" ]; then
+  eerror "First build ${CD_TARGET} kernel in \"${CD_TARGET_DIR}\" first, exiting"; exit 0
 fi
 
-if [ -d "${TARGET_DIR}" ]; then
+if [ -d "${CD_TARGET_DIR}" ]; then
   
+  ebegin "Installing RPi3 firmware in ${CD_TARGET_DIR}"
+
   if [ ! -d "/tmp/rpi-firmware" ]; then
-    git clone --depth=1 https://github.com/raspberrypi/firmware.git /tmp/rpi-firmware
+    git clone --depth=1 https://github.com/raspberrypi/firmware.git "/tmp/rpi-firmware" || cd_die
   fi
 
-  mkdir -p ${TARGET_DIR}/boot
-  cp -rav /tmp/rpi-firmware/boot/* ${TARGET_DIR}/boot/
-  cp -av ${TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image ${TARGET_DIR}/boot/kernel8.img
-  cp -av ${TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b.dtb ${TARGET_DIR}/boot
-  cp -av ${TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b-plus.dtb ${TARGET_DIR}/boot
+  mkdir -p ${CD_TARGET_DIR}/boot
+  cp -rav /tmp/rpi-firmware/boot/* "${CD_TARGET_DIR}/boot/" || cd_die
+  cp -av "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image" "${CD_TARGET_DIR}/boot/kernel8.img" || cd_die
+  cp -av "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b.dtb" "${CD_TARGET_DIR}/boot" || cd_die
+  cp -av "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b-plus.dtb" "${CD_TARGET_DIR}/boot" || cd_die
 
+  eend 0
+
+else 
+  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot install RPi3 firmware"
 fi
diff --git a/crossdev-mount b/crossdev-mount
--- a/crossdev-mount
+++ b/crossdev-mount
@@ -1,32 +1,39 @@
 #!/bin/bash
 
-TARGET=$1
-shift
-TARGET_DIR=$1
-shift
-SCRIPT_DIR=$(dirname "$0")
+CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
+CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")
 
-if [[ -z "${TARGET_DIR}" ]]; then
-  TARGET_DIR="/usr/${TARGET}"
+source "${CD_SCRIPT_DIR}/crossdev-functions.sh"
+
+cd_parse_arguments $@
+
+if [[ ! -z "${CD_HELP}" ]]; then
+  cd_print_usage_header
+  exit 1
 fi
 
-is_mount() {
-  path=$(readlink -f $1)
-  grep -q "$path" /proc/mounts
-}
+if [ -d "${CD_TARGET_DIR}" ]; then
 
-if [ -d "${TARGET_DIR}" ]; then
+  ebegin "Mounting ${CD_TARGET_DIR}/sys"
+  mkdir -p "${CD_TARGET_DIR}/sys" || cd_die
+  cd_is_mount "${CD_TARGET_DIR}/sys" || mount --bind /sys "${CD_TARGET_DIR}/sys" || cd_die
+  eend 0
 
-  mkdir -p ${TARGET_DIR}/sys
-  is_mount ${TARGET_DIR}/sys || mount --bind /sys ${TARGET_DIR}/sys
+  ebegin "Mounting ${CD_TARGET_DIR}/dev"
+  mkdir -p "${CD_TARGET_DIR}/dev" || cd_die
+  cd_is_mount "${CD_TARGET_DIR}/dev" || mount --bind /dev "${CD_TARGET_DIR}/dev" || cd_die
+  eend 0
 
-  mkdir -p ${TARGET_DIR}/dev
-  is_mount ${TARGET_DIR}/dev || mount --bind /dev ${TARGET_DIR}/dev
+  ebegin "Mounting ${CD_TARGET_DIR}/proc"
+  mkdir -p "${CD_TARGET_DIR}/proc" || cd_die
+  cd_is_mount "${CD_TARGET_DIR}/proc" || mount --bind /proc "${CD_TARGET_DIR}/proc" || cd_die
+  eend 0
 
-  mkdir -p ${TARGET_DIR}/proc
-  is_mount ${TARGET_DIR}/proc || mount --bind /proc ${TARGET_DIR}/proc
+  ebegin "Mounting ${CD_TARGET_DIR}/dev/pts"
+  mkdir -p "${CD_TARGET_DIR}/dev/pts" || cd_die
+  cd_is_mount "${CD_TARGET_DIR}/dev/pts" || mount --bind /dev/pts "${CD_TARGET_DIR}/dev/pts" || cd_die
+  eend 0
 
-  mkdir -p ${TARGET_DIR}/dev/pts
-  is_mount ${TARGET_DIR}/dev/pts || mount --bind /dev/pts ${TARGET_DIR}/dev/pts
-
+else 
+  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot mount"
 fi
diff --git a/crossdev-umount b/crossdev-umount
--- a/crossdev-umount
+++ b/crossdev-umount
@@ -1,25 +1,35 @@
 #!/bin/bash
 
-TARGET=$1
-shift
-TARGET_DIR=$1
-shift
-SCRIPT_DIR=$(dirname "$0")
+CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
+CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")
 
-if [[ -z "${TARGET_DIR}" ]]; then
-  TARGET_DIR="/usr/${TARGET}"
+source "${CD_SCRIPT_DIR}/crossdev-functions.sh"
+
+cd_parse_arguments $@
+
+if [[ ! -z "${CD_HELP}" ]]; then
+  cd_print_usage_header
+  exit 1
 fi
 
-is_mount() {
-  path=$(readlink -f $1)
-  grep -q "$path" /proc/mounts
-}
+if [ -d "${CD_TARGET_DIR}" ]; then
 
-if [ -d "${TARGET_DIR}" ]; then
+  ebegin "Unmounting ${CD_TARGET_DIR}/dev/pts"
+  cd_is_mount "${CD_TARGET_DIR}/dev/pts" && (umount -R "${CD_TARGET_DIR}/dev/pts" || cd_die)
+  eend 0
 
-  is_mount ${TARGET_DIR}/sys && umount -R ${TARGET_DIR}/sys
-  is_mount ${TARGET_DIR}/dev && umount -R ${TARGET_DIR}/dev
-  is_mount ${TARGET_DIR}/proc && umount -R ${TARGET_DIR}/proc
-  is_mount ${TARGET_DIR}/dev/pts && umount -R ${TARGET_DIR}/dev/pts
+  ebegin "Unmounting ${CD_TARGET_DIR}/proc"
+  cd_is_mount "${CD_TARGET_DIR}/proc" && (umount -R "${CD_TARGET_DIR}/proc" || cd_die)
+  eend 0
 
+  ebegin "Unmounting ${CD_TARGET_DIR}/dev"
+  cd_is_mount "${CD_TARGET_DIR}/dev" && (umount -R "${CD_TARGET_DIR}/dev" || cd_die)
+  eend 0
+
+  ebegin "Unmounting ${CD_TARGET_DIR}/sys"
+  cd_is_mount "${CD_TARGET_DIR}/sys" && (umount -R "${CD_TARGET_DIR}/sys" || cd_die)
+  eend 0
+
+else 
+  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot unmount"
 fi
