Added python to bootstrap Cow environment is now working including wrapper virtualization Changed code to be more POSIX compliant

diff --git a/crossdev-bootstrap b/crossdev-bootstrap
--- a/crossdev-bootstrap
+++ b/crossdev-bootstrap
@@ -71,7 +71,7 @@ cd_parse_extra_arguments() {
 
 cd_parse_extra_arguments "${CD_ARGS[@]}"
 
-if [[ ! -z "${CD_HELP}" ]]; then
+if [ ! -z "${CD_HELP}" ]; then
   cd_print_usage_header
   echo "--cd-use-rpi (Use RPi supported kernel)"
   echo "--cd-use-musl (Use musl as the libc)"
@@ -81,27 +81,27 @@ if [[ ! -z "${CD_HELP}" ]]; then
   echo "--cd-kernel-ver <version> (Override kernel version to use)"
   echo "--cd-binutils-ver <version> (Override binutils version to use)"
   echo "--cd-use-ver-target (Use same versions as on target)"
-  echo "--cd-use-ver-host (Use same versions as on host, default)"
+  echo "--cd-use-ver-host (Use same versions as on host)"
   exit 1
 fi
 
-if [[ "${CD_USE_VER}" == "host" ]]; then
+if [ "${CD_USE_VER}" == "host" ]; then
   CD_GET_PACKAGE_DIR="${CD_PREFIX_DIR}"
   einfo "Basing on host package versions"
 fi
 
-if [[ "${CD_USE_VER}" == "target" ]]; then
+if [ "${CD_USE_VER}" == "target" ]; then
   CD_GET_PACKAGE_DIR="${CD_TARGET_DIR}"
   einfo "Basing on target package versions"
 fi
 
-if [[ -z "${CD_USE_LIBC}" ]]; then
+if [ -z "${CD_USE_LIBC}" ]; then
   CD_HAS_MUSL=$(cd_get_package_version_by_atom "${CD_GET_PACKAGE_DIR}" "%{PVR}" "sys-libs/musl")
-  if [[ ! -z "${CD_HAS_MUSL}" ]]; then
+  if [ ! -z "${CD_HAS_MUSL}" ]; then
     CD_USE_LIBC="musl"
   fi
   CD_HAS_GLIBC=$(cd_get_package_version_by_atom "${CD_GET_PACKAGE_DIR}" "%{PVR}" "sys-libs/glibc")
-  if [[ ! -z "${CD_HAS_GLIBC}" ]]; then
+  if [ ! -z "${CD_HAS_GLIBC}" ]; then
     CD_USE_LIBC="glibc"
   fi
 fi
@@ -109,13 +109,13 @@ fi
 CD_CROSSDEV_EMERGE_ARGS+=("sys-apps/baselayout")
 
 CD_CROSSDEV_EMERGE_ARGS+=("virtual/libc")
-if [[ "${CD_USE_LIBC}" == "musl" ]]; then
-  if [[ ! -z "${CD_LIBC_VER}" ]]; then
+if [ "${CD_USE_LIBC}" == "musl" ]; then
+  if [ ! -z "${CD_LIBC_VER}" ]; then
     einfo "Using musl version: ${CD_LIBC_VER}";
     CD_CROSSDEV_EMERGE_ARGS+=("sys-libs/musl-${CD_LIBC_VER}")
   else
     CD_LIBC_VER=$(cd_get_package_version_by_atom "${CD_GET_PACKAGE_DIR}" "%{PVR}" "sys-libs/musl")
-    if [[ ! -z "${CD_LIBC_VER}" ]]; then
+    if [ ! -z "${CD_LIBC_VER}" ]; then
       einfo "No musl version specified, using: ${CD_LIBC_VER}";
       CD_CROSSDEV_EMERGE_ARGS+=("sys-libs/musl-${CD_LIBC_VER}")
     else
@@ -124,13 +124,13 @@ if [[ "${CD_USE_LIBC}" == "musl" ]]; then
     fi
   fi
 fi
-if [[ "${CD_USE_LIBC}" == "glibc" ]]; then
-  if [[ ! -z "${CD_LIBC_VER}" ]]; then
+if [ "${CD_USE_LIBC}" == "glibc" ]; then
+  if [ ! -z "${CD_LIBC_VER}" ]; then
     einfo "Using glibc version: ${CD_LIBC_VER}";
     CD_CROSSDEV_EMERGE_ARGS+=("=sys-libs/glibc-${CD_LIBC_VER}")
   else
     CD_LIBC_VER=$(cd_get_package_version_by_atom "${CD_GET_PACKAGE_DIR}" "%{PVR}" "sys-libs/glibc")
-    if [[ ! -z "${CD_LIBC_VER}" ]]; then
+    if [ ! -z "${CD_LIBC_VER}" ]; then
       einfo "No glibc version specified, using: ${CD_LIBC_VER}";
       CD_CROSSDEV_EMERGE_ARGS+=("=sys-libs/glibc-${CD_LIBC_VER}")
     else
@@ -141,17 +141,17 @@ if [[ "${CD_USE_LIBC}" == "glibc" ]]; then
 fi
 
 CD_CROSSDEV_EMERGE_ARGS+=("virtual/os-headers")
-if [[ ! -z "${CD_KERNEL_VER}" ]]; then
+if [ ! -z "${CD_KERNEL_VER}" ]; then
   einfo "Using kernel version: ${CD_KERNEL_VER}";
   CD_CROSSDEV_EMERGE_ARGS+=("=sys-kernel/linux-headers-${CD_KERNEL_VER}")
 else
-  if [[ ! -z "${CD_USE_RPI}" ]]; then
+  if [ ! -z "${CD_USE_RPI}" ]; then
     CD_KERNEL_VER="4.19"
     einfo "Using rpi kernel version: ${CD_KERNEL_VER}";
     CD_CROSSDEV_EMERGE_ARGS+=("=sys-kernel/linux-headers-${CD_KERNEL_VER}")
   else
     CD_KERNEL_VER=$(cd_get_package_version_by_atom "${CD_GET_PACKAGE_DIR}" "%{PVR}" "sys-kernel/linux-headers")
-    if [[ ! -z "${CD_KERNEL_VER}" ]]; then
+    if [ ! -z "${CD_KERNEL_VER}" ]; then
       einfo "No kernel version specified, using: ${CD_KERNEL_VER}";
       CD_CROSSDEV_EMERGE_ARGS+=("=sys-kernel/linux-headers-${CD_KERNEL_VER}")
     else
@@ -161,12 +161,12 @@ else
   fi
 fi
 
-if [[ ! -z "${CD_GCC_VER}" ]]; then
+if [ ! -z "${CD_GCC_VER}" ]; then
   einfo "Using gcc version: ${CD_GCC_VER}";
   CD_CROSSDEV_EMERGE_ARGS+=("=sys-devel/gcc-${CD_GCC_VER}")
 else
   CD_GCC_VER=$(cd_get_package_version_by_path "${CD_GET_PACKAGE_DIR}" "%{PVR}" "/usr/bin/gcc")
-  if [[ ! -z "${CD_GCC_VER}" ]]; then
+  if [ ! -z "${CD_GCC_VER}" ]; then
     einfo "No gcc version specified, using: ${CD_GCC_VER}";
     CD_CROSSDEV_EMERGE_ARGS+=("=sys-devel/gcc-${CD_GCC_VER}")
   else
@@ -175,12 +175,12 @@ else
   fi
 fi
 
-if [[ ! -z "${CD_BINUTILS_VER}" ]]; then
+if [ ! -z "${CD_BINUTILS_VER}" ]; then
   einfo "Using binutils version: ${CD_BINUTILS_VER}";
   CD_CROSSDEV_EMERGE_ARGS+=("=sys-devel/binutils-${CD_BINUTILS_VER}")
 else
   CD_BINUTILS_VER=$(cd_get_package_version_by_path "${CD_GET_PACKAGE_DIR}" "%{PVR}" "/usr/bin/ld")
-  if [[ ! -z "${CD_BINUTILS_VER}" ]]; then
+  if [ ! -z "${CD_BINUTILS_VER}" ]; then
     einfo "No binutils version specified, using: ${CD_BINUTILS_VER}";
     CD_CROSSDEV_EMERGE_ARGS+=("=sys-devel/binutils-${CD_BINUTILS_VER}")
   else
@@ -189,7 +189,23 @@ else
   fi
 fi
 
-if [[ -f "${CD_CONFIG_DIR}/crossdev-bootstrap-pre" ]]; then
+CD_PYTHON_VERS=$(cd_portageq "${CD_TARGET_DIR}" envvar USE_PYTHON)
+if [ ! -z "${CD_PYTHON_VERS}" ]; then
+  einfo "Using python versions (from target profile): ${CD_PYTHON_VERS}";
+else
+  CD_PYTHON_VERS=$(cd_portageq "${CD_PREFIX_DIR}" envvar USE_PYTHON)
+  if [ ! -z "${CD_PYTHON_VERS}" ]; then
+    einfo "Using python versions (from host profile): ${CD_PYTHON_VERS}";
+  else
+    eerror "Cannot find any python versions in host or target profile"
+    exit 1
+  fi
+fi
+for CD_PYTHON_VER in ${CD_PYTHON_VERS}; do
+  CD_CROSSDEV_EMERGE_ARGS+=("=dev-lang/python-${CD_PYTHON_VER}*")
+done
+
+if [ -f "${CD_CONFIG_DIR}/crossdev-bootstrap-pre" ]; then
   ebegin "Executing crossdev bootstrap pre hook"
   source "${CD_CONFIG_DIR}/crossdev-bootstrap-pre" || cd_die
   eend 0
@@ -198,23 +214,23 @@ fi
 ebegin "Writing package.mask to ${CD_TARGET_DIR}/etc/portage"
 mkdir -p "${CD_TARGET_DIR}/etc/portage/package.mask/" || cd_die
 
-if [[ ! -z "${CD_GCC_VER}" ]]; then
+if [ ! -z "${CD_GCC_VER}" ]; then
 cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/gcc"
 >sys-devel/gcc-${CD_GCC_VER}
 <sys-devel/gcc-${CD_GCC_VER}
 EOF
 fi
 
-if [[ ! -z "${CD_LIBC_VER}" ]]; then
+if [ ! -z "${CD_LIBC_VER}" ]; then
 
-if [[ "${CD_USE_LIBC}" == "musl" ]]; then
+if [ "${CD_USE_LIBC}" == "musl" ]; then
 cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/musl"
 >sys-libs/musl-${CD_LIBC_VER}
 <sys-libs/musl-${CD_LIBC_VER}
 EOF
 fi
 
-if [[ "${CD_USE_LIBC}" == "glibc" ]]; then
+if [ "${CD_USE_LIBC}" == "glibc" ]; then
 cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/glibc"
 >sys-libs/glibc-${CD_LIBC_VER}
 <sys-libs/glibc-${CD_LIBC_VER}
@@ -223,14 +239,14 @@ fi
 
 fi
 
-if [[ ! -z "${CD_BINUTILS_VER}" ]]; then
+if [ ! -z "${CD_BINUTILS_VER}" ]; then
 cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/binutils"
 >sys-devel/binutils-${CD_BINUTILS_VER}
 <sys-devel/binutils-${CD_BINUTILS_VER}
 EOF
 fi
 
-if [[ ! -z "${CD_KERNEL_VER}" ]]; then
+if [ ! -z "${CD_KERNEL_VER}" ]; then
 cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/linux-headers"
 >sys-kernel/linux-headers-${CD_KERNEL_VER}
 <sys-kernel/linux-headers-${CD_KERNEL_VER}
@@ -240,8 +256,7 @@ fi
 eend 0
 
 ebegin "Starting crossdev emerge with: ${CD_CROSSDEV_EMERGE_ARGS[*]}"
-export CD_TARGET CD_TARGET_DIR CD_CONFIG_DIR
-${CD_SCRIPT_DIR}/crossdev-emerge --ask --tree --usepkg-exclude="*" "${CD_CROSSDEV_EMERGE_ARGS[@]}" || cd_die
+"${CD_SCRIPT_DIR}/crossdev-emerge" --ask --tree --usepkg-exclude="*" "${CD_CROSSDEV_EMERGE_ARGS[@]}" || cd_die
 eend 0
 
 ebegin "Linking lib64 dirs to lib dirs, if possible"
@@ -249,7 +264,7 @@ ln -fs ./lib "${CD_TARGET_DIR}/usr/lib64"
 ln -fs ./lib "${CD_TARGET_DIR}/lib64"
 eend 0
 
-if [[ -f "${CD_CONFIG_DIR}/crossdev-bootstrap-post" ]]; then
+if [ -f "${CD_CONFIG_DIR}/crossdev-bootstrap-post" ]; then
   ebegin "Executing crossdev bootstrap post hook"
   source "${CD_CONFIG_DIR}/crossdev-bootstrap-post" || cd_die
   eend 0
diff --git a/crossdev-cow-env-init b/crossdev-cow-env-init
--- a/crossdev-cow-env-init
+++ b/crossdev-cow-env-init
@@ -6,33 +6,46 @@ source "${CD_CUR_DIR}/crossdev-functions.sh"
 
 cd_parse_arguments $@
 
-if [[ ! -z "${CD_HELP}" ]]; then
+if [ ! -z "${CD_HELP}" ]; then
   cd_print_usage_header
   exit 1
 fi
 
-CD_COW_PREFIX_DIR=${CD_TMP_DIR}/cow-${CD_TARGET}
-CD_UNION_PREFIX_DIR=${CD_TMP_DIR}/union-${CD_TARGET}
+export CD_COW_DIR=${CD_TMP_DIR}/cow-${CD_TARGET}
+export CD_UNION_DIR=${CD_TMP_DIR}/union-${CD_TARGET}
 
-mkdir -p "${CD_COW_PREFIX_DIR}"
-mkdir -p "${CD_UNION_PREFIX_DIR}"
+mkdir -p "${CD_COW_DIR}"; mkdir -p "${CD_UNION_DIR}"
 
-if [[ -f "${CD_CONFIG_DIR}/crossdev-cow-env-init-pre" ]]; then
-  ebegin "Executing crossdev cow env init pre hook"
-  source "${CD_CONFIG_DIR}/crossdev-cow-env-init-pre" || cd_die
+export CD_WRAPPER_DIR=${CD_TMP_DIR}/wrapper-cow-${CD_TARGET}
+export CD_WRAPPER_PREFIX_DIR=${CD_TMP_DIR}/wrapper-cow-${CD_TARGET}/usr
+export CD_WRAPPER_INSTALL_DIR=${CD_TMP_DIR}/wrapper-cow-${CD_TARGET}/usr
+
+if ! cd_is_mount "${CD_UNION_PREFIX_DIR}"; then
+
+  if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-init-pre" ]; then
+    ebegin "Executing crossdev cow env init pre hook"
+    source "${CD_CONFIG_DIR}/crossdev-cow-env-init-pre" || cd_die
+    eend 0
+  fi
+
+  ebegin "Initializing cow environment"
+
+  ebegin "Creating wrapper environment"
+  source "${CD_SCRIPT_DIR}/crossdev-wrapper-env-create" "${CD_ARGS[@]}" || cd_die
   eend 0
-fi
 
-ebegin "Initializing environment"
-
-ebegin "Mounting union"
-unionfs -o cow "${CD_COW_PREFIX_DIR}"=RW:/=RO "${CD_UNION_PREFIX_DIR}" || cd_die
-eend 0
-
-eend 0
-
-if [[ -f "${CD_CONFIG_DIR}/crossdev-cow-env-init-post" ]]; then
-  ebegin "Executing crossdev cow env init post hook"
-  source "${CD_CONFIG_DIR}/crossdev-cow-env-init-post" || cd_die
+  ebegin "Mounting unionfs"
+  unionfs -o cow "${CD_COW_DIR}"=RW:"${CD_WRAPPER_DIR}"=RO:/=RO "${CD_UNION_DIR}" || cd_die
   eend 0
+
+  eend 0
+
+  if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-init-post" ]; then
+    ebegin "Executing crossdev cow env init post hook"
+    source "${CD_CONFIG_DIR}/crossdev-cow-env-init-post" || cd_die
+    eend 0
+  fi
+   
+else
+  eerror "Cow environment already mounted, cannot initialize"
 fi
